server:
  port: 8080

spring:
  application:
    name: gateway_service

  cloud:
    gateway:
      routes:
        - id: clients-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/clients/**

        - id: products-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/products/**

        - id: orders-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/orders/**

        - id: auth-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/auth/**

        - id: invoices-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/invoices/**

        - id: inventory-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/inventory/**
        
        - id: users-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/users/**
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always
